theme: minima
title: what is cloud?
author: Harshitha-staker
email: harshitha1681@gmail.com
description: > # this means to ignore newlines until "baseurl:"
"The cloud" refers to servers that are accessed over the Internet, and the software and databases
that run on those servers. Cloud servers are located in data centers all over the world. By using cloud computing,
users and companies don't have to manage physical servers themselves or run software applications on their own machines.



# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
